name: 'Firmware Update Action'
description: 'Update firmware version and url on the server'
inputs:
  firmware-wifi-url:
    description: 'Url to the firmware WiFi build'
    default: ''
  firmware-eth-url:
    description: 'Url to the firmware Ethernet build'
    default: ''
  firmware-version:
    description: 'Firmware version'
    default: ''
  web-server-url:
    description: 'Url to the web server'
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Update firmware on the server
      if: ${{ inputs.firmware-wifi-url != '' && inputs.firmware-eth-url != '' && inputs.firmware-version != '' && inputs.web-server-url != '' }}
      shell: bash
      run: |
        echo "Updating firmware version to ${{ inputs.firmware-version }}"
        echo "Updating firmware WiFi binary url to ${{ inputs.firmware-wifi-url }}"
        echo "Updating firmware Ethernet binary url to ${{ inputs.firmware-eth-url }}"
        # Update firmware version and urls on the server
        curl -X POST -H "Content-Type: application/json" -d '{"firmware_version": "${{ inputs.firmware-version }}", "firmware_wifi_url": "${{ inputs.firmware-wifi-url }}", "firmware_eth_url": "${{ inputs.firmware-eth-url }}"}' ${{ inputs.web-server-url }}

