[common]
platform = espressif32@7.0.1
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = min_spiffs.csv
lib_deps =
    https://github.com/MatheusAlvesA/ArduinoAsync.git
    bblanchon/ArduinoJson@7.4.3
    gilmaimon/ArduinoWebsockets@0.5.4
    tzapu/WiFiManager@2.0.17

[env:grid_detector_wifi]
extends = common
build_flags =
    -D WIFI=1
    -D ETHERNET=0
    -D GRID=1
    -D ARDUINO_OTA_ENABLED=1

[env:grid_detector_eth]
extends = common
build_flags =
    -D WIFI=0
    -D ETHERNET=1
    -D GRID=1
    -D ARDUINO_OTA_ENABLED=1
