name: 🏗️ Compile Firmware
on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - master
  workflow_dispatch:
jobs:
  compile_grid_detector:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compile Grid Detector firmware (all environments)
        uses: ./.github/workflows/firmware-compile
        with:
          project-folder: grid_detector
      - name: Upload WiFi firmware
        uses: actions/upload-artifact@v4
        with:
          name: grid_detector_wifi.bin
          path: ${{ github.workspace }}/grid_detector/.pio/build/grid_detector_wifi/firmware.bin
      - name: Upload Ethernet firmware
        uses: actions/upload-artifact@v4
        with:
          name: grid_detector_eth.bin
          path: ${{ github.workspace }}/grid_detector/.pio/build/grid_detector_eth/firmware.bin

  compile_flasher:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compile Flasher firmware
        uses: ./.github/workflows/firmware-compile
        with:
          project-folder: flasher
